<a href="https://colab.research.google.com/github/aboelela924/Deep-learning-with-TF2-and-Keras/blob/master/Deep_learning_with_TF2_and_Keras_chapter_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow.compat.v1 as tf
# tf.disable_eager_execution()

In [ ]:
def separator():
    print("\n*------------------------------------------------*\n")

<h1>Computational graphs</h1>

In [ ]:
v1 = tf.constant([1,2,3,4])
v2 = tf.constant([2,1,5,3])
operation = tf.add(v1, v2)
with tf.Session() as sess:
    print(sess.run(operation))

[3 3 8 7]


In [ ]:

t_1 = tf.constant(1)
t_2 = tf.constant([1,2,3,4,5,6,78,9])
t_zeros = tf.zeros((3,4), tf.int32)

print(t_1)
separator()
print(t_2)
separator()
print(t_zeros)
separator()
print(t_zeros.shape)

tf.Tensor(1, shape=(), dtype=int32)

*------------------------------------------------*

tf.Tensor([ 1  2  3  4  5  6 78  9], shape=(8,), dtype=int32)

*------------------------------------------------*

tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)

*------------------------------------------------*

(3, 4)


In [ ]:
t = tf.Variable([[0,1,2],
                 [3,4,5],
                 [6,7,8]])
print(t*2)

tf.Tensor(
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]], shape=(3, 3), dtype=int32)


In [ ]:
range_t = tf.linspace(2.0, 5.0, 5)
print(range_t)

tf.Tensor([2.   2.75 3.5  4.25 5.  ], shape=(5,), dtype=float32)


In [ ]:
print(tf.range(10))

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [ ]:
t_random = tf.random_normal((2,3), mean=2.0, stddev=4, seed=12)
print(t_random)
t_random_truncated = tf.truncated_normal((1,5), stddev=4, seed=12)
print(t_random_truncated)
t_random_maxed = tf.random_uniform((1,5), maxval=4, seed=12)
print(t_random_maxed)
print(tf.random_crop(t_random, (1,2), seed=12))
print(tf.random_shuffle(t_random))


tf.Tensor(
[[ 4.141584  -2.4323368  1.4757246]
 [ 3.939736   2.7487824  4.4081745]], shape=(2, 3), dtype=float32)
tf.Tensor([[ 4.761191    3.7189643  -1.5012052  -3.4287133  -0.46264905]], shape=(1, 5), dtype=float32)
tf.Tensor([[2.0150442 1.667253  2.4221244 3.6843219 3.673421 ]], shape=(1, 5), dtype=float32)
tf.Tensor([[2.7487824 4.4081745]], shape=(1, 2), dtype=float32)
tf.Tensor(
[[ 3.939736   2.7487824  4.4081745]
 [ 4.141584  -2.4323368  1.4757246]], shape=(2, 3), dtype=float32)


<h3>Variables</h3>

In [ ]:
rand_t = tf.random_uniform((50, 50), 0, 10, seed=0)
t_a = tf.Variable(rand_t)
t_b = tf.Variable(rand_t)
print(t_a)
print(t_b)

In [ ]:
weights = tf.Variable(tf.random_normal((100, 100),  stddev=4))
bias = tf.Variable(tf.zeros(100), name="bias")

<h1>An example of TensorFlow 1.x in TensorFlow 2.x</h1>

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

in_a = tf.placeholder(dtype=tf.float32, shape=(2,))
def model(x):
    with tf.variable_scope("matmul"):
        W = tf.get_variable("W", initializer=tf.ones(shape=(2,2)))
        b = tf.get_variable("b", initializer=tf.zeros(shape=(2,1)))
        return x * W + b

out_a = model(in_a)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    out = sess.run([out_a], feed_dict={in_a: [1, 0]})
    writer = tf.summary.FileWriter("/content/example", sess.graph) 

In [ ]:
import tensorboard

In [ ]:
!docker run -it -p 8888:8888 -p 6006:6006 \
tensorflow/tensorflow:nightly-py3-jupyter 

/bin/bash: docker: command not found


In [ ]:
%load_ext tensorboard
%tensorboard --logdir example

In [ ]:
import tensorflow as tf
def linear_layer(x):
    return 3*x+2

@tf.function
def simple_nn():
    return tf.nn.relu(linear_layer(x))

def simple_function(x):
    return 3*x

In [ ]:
print(simple_nn)
print(simple_function)

<function simple_function at 0x7f7a2cdd28c8>


In [ ]:
print(tf.autograph.to_code(simple_nn.python_function))

def tf__simple_nn():
    with ag__.FunctionScope('simple_nn', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        try:
            do_return = True
            retval_ = ag__.converted_call(ag__.ld(tf).nn.relu, (ag__.converted_call(ag__.ld(linear_layer), (ag__.ld(x),), None, fscope),), None, fscope)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)



<h1>Functional API</h1>

In [ ]:
import tensorflow as tf 

def build_model():
    text_input_a = tf.keras.Input(shape=(None, ), dtype="int32")
    text_input_b = tf.keras.Input(shape=(None, ), dtype="int32")
    shared_embedding = tf.keras.layers.Embedding(1000, 128)
    encoded_input_a = shared_embedding(text_input_a)
    encoded_input_b = shared_embedding(text_input_b)
    prediction_a = tf.keras.layers.Dense(1, activation="sigmoid", name="prediction_a")(encoded_input_a)
    prediction_b = tf.keras.layers.Dense(1, activation="sigmoid", name="prediction_b")(encoded_input_b)

    model = tf.keras.Model(inputs=[text_input_a, text_input_b], 
                           outputs=[prediction_a, prediction_b])
    tf.keras.utils.plot_model(model, "/content/shared_model.png")

build_model()

<h1>Model subclassing</h1>

In [13]:
class MyLayer(tf.keras.layers.Layer):
    
    def __init__(self, output_dim, **args):
        self.output_dim = output_dim
        super(MyLayer, self).__init__(**args)

    def build(self, input_shape):
        self.kernel = self.add_weight(name="kernel", 
                                      shape=(input_shape[1], self.output_dim),
                                      initializer="uniform", 
                                      trainable=True)
        
    def call(self, inputs):
        return tf.matmul(inputs, self.kernel)

<h1>Estimators</h>

In [17]:
import tensorflow as tf
import tensorflow_datasets as tfds
BUFFER_SIZE = 10000
BATCH_SIZE = 64
def input_fn(mode):
    datasets, info = tfds.load(name='mnist',
    with_info=True,
    as_supervised=True)
    mnist_dataset = (datasets['train'] if mode == tf.estimator.ModeKeys.
    TRAIN else datasets['test'])
def scale(image, label):
    image = tf.cast(image, tf.float32)
    image /= 255
    return image, label
    return mnist_dataset.map(scale).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)
test = input_fn('test')
train = input_fn(tf.estimator.ModeKeys.TRAIN)
print(test)
print(train)

local data directory. If you'd instead prefer to read directly from our public
GCS bucket (recommended if you're running on GCP), you can instead set
data_dir=gs://tfds-data/datasets.





Dataset mnist downloaded and prepared to /root/tensorflow_datasets/mnist/3.0.0. Subsequent calls will reuse this data.
None
None
